# Generated by Django 6.0.3 on 2026-03-23 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doi', models.CharField(blank=True, help_text='Ex: 10.xxxx/rgiu.2026.001', max_length=150, unique=True, verbose_name='DOI')),
                ('journal_name', models.CharField(default='Portfolio HPB · Articles', max_length=200, verbose_name='Nom de la revue')),
                ('volume', models.CharField(blank=True, default='Vol. 1', max_length=50, verbose_name='Volume / numéro')),
                ('year', models.IntegerField(default=2026, verbose_name='Année')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='Image de couverture (OG)')),
                ('title_fr', models.CharField(max_length=500, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (EN)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (AR)')),
                ('subtitle_fr', models.CharField(blank=True, default='', max_length=500, verbose_name='Sous-titre (FR)')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Sous-titre (EN)')),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Sous-titre (AR)')),
                ('abstract_fr', models.TextField(verbose_name='Résumé (FR)')),
                ('abstract_en', models.TextField(blank=True, default='', verbose_name='Abstract (EN)')),
                ('abstract_ar', models.TextField(blank=True, default='', verbose_name='الملخص (AR)')),
                ('keywords_fr', models.CharField(blank=True, default='', max_length=500, verbose_name='Mots-clés FR (virgules)')),
                ('keywords_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Keywords EN (commas)')),
                ('keywords_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='كلمات مفتاحية (فواصل)')),
                ('key_metrics', models.JSONField(blank=True, default=list, help_text='Ex: [{"label":"Réseau cartographié","value":"1 015","unit":"km","icon":"🛣️"},{"label":"PCI moyen","value":"46.0","unit":"","icon":"📊"}]', verbose_name='Statistiques clés (JSON)')),
                ('content_sections', models.JSONField(blank=True, default=list, help_text='Structure: [{"order":1,"slug":"introduction","title_fr":"Introduction","title_en":"Introduction","title_ar":"مقدمة","content_fr":"<p>...</p>","content_en":"","content_ar":""}]', verbose_name="Sections de l'article (JSON)")),
                ('references', models.JSONField(blank=True, default=list, help_text='Ex: ["ASTM (2020). D6433-20...","Banque mondiale (2023)..."]', verbose_name='Références bibliographiques (JSON)')),
                ('meta_description_fr', models.TextField(blank=True, default='')),
                ('meta_description_en', models.TextField(blank=True, default='')),
                ('meta_description_ar', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-published_at', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre (Dr, Pr, Ing…)')),
                ('affiliation', models.CharField(blank=True, max_length=300, verbose_name='Affiliation / Institution')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, help_text='Ex: 0000-0001-2345-6789', max_length=50, verbose_name='ORCID iD')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('is_corresponding', models.BooleanField(default=False, verbose_name='Auteur correspondant')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Photo')),
                ('bio_fr', models.TextField(blank=True, verbose_name='Biographie (FR)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Biography (EN)')),
            ],
            options={
                'verbose_name': 'Auteur',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVProtege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='cv/', verbose_name='Fichier CV (PDF)')),
                ('code', models.CharField(max_length=50, verbose_name="Code d'accès")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('nom_fichier', models.CharField(default='CV_Hilla_Prince_Bambe.pdf', max_length=100, verbose_name='Nom téléchargé')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV Protégé',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('institution_fr', models.CharField(blank=True, default='', max_length=200)),
                ('institution_en', models.CharField(blank=True, default='', max_length=200)),
                ('institution_ar', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('company_fr', models.CharField(blank=True, default='', max_length=200)),
                ('company_en', models.CharField(blank=True, default='', max_length=200)),
                ('company_ar', models.CharField(blank=True, default='', max_length=200)),
                ('period', models.CharField(blank=True, default='', max_length=50)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expérience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(default='Hilla Prince Bambé', max_length=100)),
                ('name_en', models.CharField(default='Hilla Prince Bambé', max_length=100)),
                ('name_ar', models.CharField(default='هيلا برانس بامبي', max_length=100)),
                ('title_fr', models.CharField(default='Chargé de Projet', max_length=200)),
                ('title_en', models.CharField(default='Project Manager', max_length=200)),
                ('title_ar', models.CharField(default='مدير مشروع', max_length=200)),
                ('bio_fr', models.TextField(blank=True, default='')),
                ('bio_en', models.TextField(blank=True, default='')),
                ('bio_ar', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('percentage', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compétence',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='articles/attachments/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('data', 'Données'), ('supplementary', 'Matériel supplémentaire'), ('code', 'Code source')], default='pdf', max_length=50)),
                ('description_fr', models.CharField(blank=True, max_length=300)),
                ('description_en', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.article')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
            options={
                'verbose_name': "Auteur d'article",
                'ordering': ['order'],
                'unique_together': {('article', 'author')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles', through='api.ArticleAuthor', to='api.author'),
        ),
    ]
