# Generated by Django 4.2.9 on 2026-03-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(max_length=300)),
                ('summary_fr', models.TextField(blank=True, default='')),
                ('summary_en', models.TextField(blank=True, default='')),
                ('summary_ar', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-file-code', max_length=50)),
                ('link', models.URLField(blank=True, default='#')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='DevOps', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('institution_fr', models.CharField(blank=True, default='', max_length=200)),
                ('institution_en', models.CharField(blank=True, default='', max_length=200)),
                ('institution_ar', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('company_fr', models.CharField(blank=True, default='', max_length=200)),
                ('company_en', models.CharField(blank=True, default='', max_length=200)),
                ('company_ar', models.CharField(blank=True, default='', max_length=200)),
                ('period', models.CharField(blank=True, default='', max_length=50)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expérience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(default='Hilla Prince Bambé', max_length=100)),
                ('name_en', models.CharField(default='Hilla Prince Bambé', max_length=100)),
                ('name_ar', models.CharField(default='هيلا برانس بامبي', max_length=100)),
                ('title_fr', models.CharField(default="Ingénieur des Technologies d'Information", max_length=200)),
                ('title_en', models.CharField(default='Information Technology Engineer', max_length=200)),
                ('title_ar', models.CharField(default='مهندس تكنولوجيا المعلومات', max_length=200)),
                ('bio_fr', models.TextField(default='Jeune ambitieux, je serai un excellent atout pour votre institution notamment dans la gestion de vos projets.')),
                ('bio_en', models.TextField(default='Young and ambitious, I will be a great asset to your institution, particularly in managing your projects.')),
                ('bio_ar', models.TextField(default='شاب طموح، سأكون أصلاً ممتازاً لمؤسستكم، لا سيما في إدارة مشاريعكم.')),
                ('email', models.EmailField(default='hillaprincebambe@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+235 60 92 87 48', max_length=30)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/prince_allih/')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/prince.sirius/')),
                ('twitter', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=50)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Compétence',
                'ordering': ['order'],
            },
        ),
    ]
