# Generated by Django 6.0.3 on 2026-03-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
    ]
