# Generated by Django 6.0.3 on 2026-03-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cvprotege'),
        ('api', '0003_remove_article_content_ar_remove_article_content_en_and_more'),
    ]

    operations = [
    ]
