"""
import_article.py — Script d'import du JSON article dans Django
Usage (PowerShell dans backend/) :
    python manage.py shell < import_article.py
OU
    python import_article.py  (si lancé depuis backend/)
"""

import os, sys, django, json

# ── Setup Django ──────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'portfolio.settings')
django.setup()

from api.models import Article, Author, ArticleAuthor
from django.utils import timezone
from django.utils.dateparse import parse_datetime

# ══════════════════════════════════════════════════════════════
#  DONNÉES — copie exacte du JSON fourni
# ══════════════════════════════════════════════════════════════
CONTENT_SECTIONS = [
    {"order":1,"slug":"introduction","title_fr":"1. Introduction","title_en":"1. Introduction","title_ar":"1. مقدمة","content_fr":"<p>Les infrastructures routières représentent l'épine dorsale du développement économique et social de toute agglomération urbaine. Elles conditionnent l'accessibilité aux services essentiels, la mobilité des personnes et des biens, l'attractivité économique et la résilience face aux aléas naturels.</p><p>N'Djamena, capitale et principal pôle économique de la République du Tchad, illustre de manière paradigmatique cette problématique. Malgré leur importance stratégique, les infrastructures routières de N'Djamena ne font l'objet d'aucune cartographie systématique, exhaustive et quantitative.</p><p>Le présent article vise à combler ce vide en proposant une approche méthodologique intégrée, innovante et reproductible, combinant géomatique avancée, photogrammétrie par drone et intelligence artificielle.</p>","content_en":"<p>Road infrastructure represents the backbone of economic and social development of any urban agglomeration. They determine accessibility to essential services, mobility of people and goods, economic attractiveness and resilience to natural hazards.</p><p>N'Djamena, capital and main economic hub of the Republic of Chad, illustrates this issue paradigmatically. Despite their strategic importance, N'Djamena's road infrastructure has never been systematically, exhaustively and quantitatively mapped.</p><p>This article aims to fill this gap by proposing an integrated, innovative and reproducible methodological approach, combining advanced geomatics, drone photogrammetry and artificial intelligence.</p>","content_ar":"<p>تمثل البنية التحتية للطرق العمود الفقري للتنمية الاقتصادية والاجتماعية لأي تجمع حضري. فهي تحدد إمكانية الوصول إلى الخدمات الأساسية، وحركة الأشخاص والبضائع، والجاذبية الاقتصادية والمرونة في مواجهة المخاطر الطبيعية.</p><p>انجمينا، العاصمة والمركز الاقتصادي الرئيسي لجمهورية تشاد، توضح هذه المشكلة بشكل مثالي.</p><p>تهدف هذه المقالة إلى سد هذه الفجوة من خلال اقتراح منهجية متكاملة ومبتكرة وقابلة للتكرار.</p>"},
    {"order":2,"slug":"objectifs-recherche","title_fr":"1.1 Objectifs de la recherche","title_en":"1.1 Research Objectives","title_ar":"1.1 أهداف البحث","content_fr":"<ul><li>Cartographier de manière exhaustive l'ensemble du réseau routier de N'Djamena, incluant les voies primaires, secondaires, tertiaires et les pistes non revêtues</li><li>Établir une nomenclature fonctionnelle structurée en cinq catégories de voies adaptée au contexte tchadien</li><li>Évaluer l'état de chaque segment routier à partir d'indices internationalement reconnus (PCI et IRI)</li><li>Mettre en œuvre une chaîne de traitement innovante intégrant le deep learning pour la détection automatisée des dégradations</li><li>Produire un tableau de bord cartographique interactif accessible aux décideurs</li><li>Formuler des recommandations stratégiques et priorisées pour la réhabilitation du réseau</li></ul>","content_en":"<ul><li>Comprehensively map the entire road network of N'Djamena, including primary, secondary, tertiary roads and unpaved tracks</li><li>Establish a functional nomenclature structured in five road categories adapted to the Chadian context</li><li>Evaluate the condition of each road segment using internationally recognized indices (PCI and IRI)</li><li>Implement an innovative processing chain integrating deep learning for automated damage detection</li><li>Produce an interactive cartographic dashboard accessible to decision-makers</li><li>Formulate strategic and prioritized recommendations for network rehabilitation</li></ul>","content_ar":"<ul><li>رسم خرائط شاملة لشبكة الطرق بأكملها في انجمينا</li><li>إنشاء تسمية وظيفية منظمة في خمس فئات من الطرق</li><li>تقييم حالة كل قطاع من الطرق باستخدام مؤشرات معترف بها دولياً</li><li>تنفيذ سلسلة معالجة مبتكرة تدمج التعلم العميق</li><li>إنتاج لوحة قيادة خرائطية تفاعلية</li><li>صياغة توصيات استراتيجية لإعادة تأهيل الشبكة</li></ul>"},
    {"order":3,"slug":"zone-etude","title_fr":"2. Zone d'étude","title_en":"2. Study Area","title_ar":"2. منطقة الدراسة","content_fr":"<p>N'Djamena (12°06'N, 15°02'E) est la capitale de la République du Tchad. Elle est située à la confluence du fleuve Chari et de son affluent le Logone, à la frontière avec le Cameroun. La ville est divisée en dix arrondissements administratifs couvrant une superficie de 294 km².</p>","content_en":"<p>N'Djamena (12°06'N, 15°02'E) is the capital of the Republic of Chad. It is located at the confluence of the Chari River and its tributary the Logone, on the border with Cameroon. The city is divided into ten administrative districts covering an area of 294 km².</p>","content_ar":"<p>انجمينا (12°06'N, 15°02'E) هي عاصمة جمهورية تشاد. تقع عند ملتقى نهر شاري وفرعه لوغون، على الحدود مع الكاميرون. تنقسم المدينة إلى عشر مقاطعات إدارية تغطي مساحة 294 كم².</p>"},
    {"order":4,"slug":"contexte-urbain","title_fr":"2.1 Contexte urbain et réseau routier","title_en":"2.1 Urban Context and Road Network","title_ar":"2.1 السياق الحضري وشبكة الطرق","content_fr":"<p>Le réseau routier estimé totalise environ 1 015 km linéaires de voies de toutes catégories. Seuls 15 à 18 % bénéficient d'un revêtement bitumineux ou bétonné, concentrés dans les arrondissements centraux (1er, 2ème, 6ème).</p><p><strong>⚠ Facteurs aggravants :</strong> Inondations saisonnières (500-600 mm/an sur 3-4 mois), trafic de poids lourds non régulé, absence de drainage sur plus de 70 % du linéaire, maintenance exclusivement curative et croissance démographique non maîtrisée.</p>","content_en":"<p>The estimated road network totals approximately 1,015 km of roads of all categories. Only 15 to 18% have bituminous or concrete pavement, concentrated in central districts (1st, 2nd, 6th).</p><p><strong>⚠ Aggravating factors:</strong> Seasonal flooding (500-600 mm/year over 3-4 months), unregulated heavy truck traffic, absence of drainage on more than 70% of the network, exclusively curative maintenance and uncontrolled demographic growth.</p>","content_ar":"<p>يبلغ إجمالي شبكة الطرق المقدرة حوالي 1015 كم من الطرق بجميع الفئات. فقط 15 إلى 18% لديها رصف إسفلتي أو خرساني.</p><p><strong>⚠ عوامل تفاقم:</strong> فيضانات موسمية، حركة شاحنات ثقيلة غير منظمة، عدم وجود صرف لأكثر من 70% من الشبكة.</p>"},
    {"order":5,"slug":"revue-litterature","title_fr":"3. Revue de littérature","title_en":"3. Literature Review","title_ar":"3. مراجعة الأدبيات","content_fr":"<p>Le Pavement Condition Index (PCI), développé par l'US Army Corps of Engineers et normalisé ASTM D6433-20, constitue la méthode de référence mondiale d'évaluation visuelle des chaussées sur une échelle de 0 à 100. L'International Roughness Index (IRI) mesure quant à lui la rugosité longitudinale du profil de chaussée.</p><p>L'émergence du deep learning a ouvert de nouvelles perspectives pour l'automatisation du diagnostic des chaussées. Les architectures YOLO, Faster R-CNN et EfficientDet permettent la détection et la classification automatique des dégradations avec des niveaux de précision proches de l'expert humain.</p>","content_en":"<p>The Pavement Condition Index (PCI), developed by the US Army Corps of Engineers and standardized ASTM D6433-20, is the world reference method for visual pavement evaluation on a 0 to 100 scale. The International Roughness Index (IRI) measures the longitudinal roughness of the pavement profile.</p><p>The emergence of deep learning has opened new perspectives for automating pavement diagnostics. CNN architectures such as YOLO, Faster R-CNN and EfficientDet enable automatic detection and classification of damages.</p>","content_ar":"<p>مؤشر حالة الرصف (PCI)، الذي طوره فيلق المهندسين بالجيش الأمريكي وتم توحيده بموجب ASTM D6433-20، هو الطريقة المرجعية العالمية للتقييم البصري للرصف على مقياس من 0 إلى 100.</p>"},
    {"order":6,"slug":"methodologie","title_fr":"4. Méthodologie","title_en":"4. Methodology","title_ar":"4. المنهجية","content_fr":"<p>La méthodologie se décompose en cinq phases successives : collecte et préparation des données, cartographie et catégorisation, évaluation PCI et IRI, détection IA (YOLOv8), et tableau de bord cartographique.</p>","content_en":"<p>The methodology is divided into five successive phases: data collection and preparation, mapping and categorization, PCI and IRI evaluation, AI detection (YOLOv8), and cartographic dashboard.</p>","content_ar":"<p>تنقسم المنهجية إلى خمس مراحل متتالية: جمع البيانات وإعدادها، الرسم الخرائطي والتصنيف، تقييم PCI و IRI، كشف الذكاء الاصطناعي (YOLOv8)، ولوحة القيادة الخرائطية.</p>"},
    {"order":7,"slug":"collecte-donnees","title_fr":"4.1 Phase 1 – Collecte et préparation des données","title_en":"4.1 Phase 1 – Data Collection and Preparation","title_ar":"4.1 المرحلة 1 – جمع البيانات وإعدادها","content_fr":"<p><strong>4.1.1 Données géospatiales de base :</strong> La constitution de la couche de base du réseau routier repose sur une extraction depuis OpenStreetMap (OSM) via l'API Overpass, complétée par des données ASTER GDEM v3 pour le modèle numérique de terrain et des images satellites Sentinel-2 (résolution 10 m).</p><p><strong>4.1.2 Levés GPS de terrain :</strong> Des campagnes de terrain sont conduites avec des récepteurs GNSS RTK (précision horizontale ≤ 2 cm) pour les axes primaires et secondaires, et des GPS de randonnée (précision ±5 m) pour les pistes tertiaires.</p><p><strong>4.1.3 Acquisition d'orthophotographies par drone :</strong> Des missions de photogrammétrie aérienne par drone (DJI Mavic 3) sont planifiées sur les zones prioritaires à forte densité de dégradations. Résolution cible : 5 cm/px, recouvrement longitudinal 80 %, transversal 70 %.</p>","content_en":"<p><strong>4.1.1 Base geospatial data:</strong> Extracted from OpenStreetMap (OSM) via Overpass API, complemented by ASTER GDEM v3 and Sentinel-2 satellite images (10 m resolution).</p><p><strong>4.1.2 Field GPS surveys:</strong> GNSS RTK receivers (≤ 2 cm precision) for primary/secondary axes, hiking GPS (±5 m) for tertiary tracks.</p><p><strong>4.1.3 Drone orthophotography:</strong> DJI Mavic 3 missions on priority areas. Target resolution: 5 cm/px, 80% longitudinal overlap, 70% transverse.</p>","content_ar":"<p><strong>4.1.1 البيانات الجغرافية الأساسية:</strong> استخراج من OpenStreetMap عبر API Overpass، مكملاً ببيانات ASTER GDEM v3 وصور Sentinel-2.</p><p><strong>4.1.2 مسوحات GPS الميدانية:</strong> أجهزة GNSS RTK (دقة ≤ 2 سم) للمحاور الرئيسية.</p>"},
    {"order":8,"slug":"cartographie-categorisation","title_fr":"4.2 Phase 2 – Cartographie et catégorisation","title_en":"4.2 Phase 2 – Mapping and Categorization","title_ar":"4.2 المرحلة 2 – الرسم الخرائطي والتصنيف","content_fr":"<p>Toutes les données sont intégrées dans une base de données géospatiale PostgreSQL/PostGIS. La classification fonctionnelle en cinq catégories (V1 primaires → V5 périurbaines) s'inspire des standards CEDEAO adaptés au contexte tchadien.</p>","content_en":"<p>All data is integrated into a PostgreSQL/PostGIS geospatial database. The functional classification into five categories (V1 primary → V5 peri-urban) is inspired by ECOWAS standards adapted to the Chadian context.</p>","content_ar":"<p>يتم دمج جميع البيانات في قاعدة بيانات جغرافية مكانية PostgreSQL/PostGIS. يستند التصنيف الوظيفي إلى خمس فئات إلى معايير الجماعة الاقتصادية لدول غرب أفريقيا.</p>"},
    {"order":9,"slug":"evaluation-pci-iri","title_fr":"4.3 Phase 3 – Évaluation PCI et IRI","title_en":"4.3 Phase 3 – PCI and IRI Evaluation","title_ar":"4.3 المرحلة 3 – تقييم PCI و IRI","content_fr":"<p>Le PCI est calculé conformément à la norme ASTM D6433-20 sur des sections de 50 m (voies bitumées) et 30 m (pistes). L'IRI est mesuré par profilométrie inertielle via accéléromètre triaxial (norme ISO 8608) et par estimation depuis le profil LiDAR extrait des orthophotos drone.</p>","content_en":"<p>PCI is calculated according to ASTM D6433-20 standard on 50 m sections (paved roads) and 30 m (tracks). IRI is measured by inertial profilometry via triaxial accelerometer (ISO 8608) and from LiDAR profile extracted from drone orthophotos.</p>","content_ar":"<p>يتم حساب PCI وفقاً لمعيار ASTM D6433-20 على أقسام 50 م (طرق معبدة) و 30 م (مسارات).</p>"},
    {"order":10,"slug":"detection-ia-yolov8","title_fr":"4.4 Phase 4 – Détection IA (YOLOv8)","title_en":"4.4 Phase 4 – AI Detection (YOLOv8)","title_ar":"4.4 المرحلة 4 – كشف الذكاء الاصطناعي (YOLOv8)","content_fr":"<p>Un pipeline de traitement automatisé est développé autour du modèle YOLOv8. Un jeu de données d'entraînement de 8 500 images annotées manuellement est constitué, complété par des données publiques (CrackForest, Road Damage Dataset). Quatre classes cibles : fissures, nids-de-poule, orniérage et déchaussement de bordure.</p><p><strong>🤖 Performance du modèle :</strong> Le modèle fine-tuné atteint une précision mAP@0.5 de 91,3 % et mAP@0.5:0.95 de 72,8 % sur le jeu de test, validant son applicabilité opérationnelle en contexte tchadien.</p>","content_en":"<p>An automated processing pipeline around YOLOv8. Training dataset of 8,500 manually annotated images. Four target classes: cracks, potholes, rutting and edge stripping.</p><p><strong>🤖 Model Performance:</strong> mAP@0.5: 91.3%, mAP@0.5:0.95: 72.8% on test set.</p>","content_ar":"<p>خط معالجة آلي حول YOLOv8. مجموعة بيانات تدريبية من 8500 صورة. أربع فئات: الشقوق، الحفر، الأخاديد وتقشير الحواف.</p><p><strong>🤖 الأداء:</strong> mAP@0.5: 91.3%، mAP@0.5:0.95: 72.8%.</p>"},
    {"order":11,"slug":"tableau-bord","title_fr":"4.5 Phase 5 – Tableau de bord cartographique","title_en":"4.5 Phase 5 – Cartographic Dashboard","title_ar":"4.5 المرحلة 5 – لوحة القيادة الخرائطية","content_fr":"<p>Un tableau de bord interactif développé en OpenLayers (frontend) et Flask/Python (backend) permet la visualisation par segment colorisé selon le PCI, le filtrage par arrondissement, la génération de rapports PDF et la saisie mobile par les agents terrain.</p>","content_en":"<p>An interactive dashboard in OpenLayers (frontend) and Flask/Python (backend) allows PCI-colored segment visualization, district filtering, PDF report generation and mobile entry by field agents.</p>","content_ar":"<p>لوحة قيادة تفاعلية بـ OpenLayers و Flask/Python تتيح التصور حسب القطاع الملون وفقاً لـ PCI، التصفية حسب المقاطعة وإنشاء تقارير PDF.</p>"},
    {"order":12,"slug":"resultats","title_fr":"5. Résultats","title_en":"5. Results","title_ar":"5. النتائج","content_fr":"<p>L'inventaire exhaustif a permis de recenser et cartographier <strong>1 015,3 km</strong> de voies sur les dix arrondissements de N'Djamena.</p>","content_en":"<p>The exhaustive inventory allowed to census and map <strong>1,015.3 km</strong> of roads across all ten districts of N'Djamena.</p>","content_ar":"<p>أتاح الجرد الشامل إحصاء ورسم خرائط <strong>1015.3 كم</strong> من الطرق عبر المقاطعات العشر في انجمينا.</p>"},
    {"order":13,"slug":"inventaire-reseau","title_fr":"5.1 Inventaire et cartographie du réseau routier","title_en":"5.1 Road Network Inventory and Mapping","title_ar":"5.1 جرد ورسم خرائط شبكة الطرق","content_fr":"<ul><li>Voies primaires V1 : <strong>84,7 km</strong> (8,3 %)</li><li>Voies secondaires V2 : <strong>141,2 km</strong> (13,9 %)</li><li>Voies tertiaires V3 : <strong>219,8 km</strong> (21,7 %)</li><li>Pistes non revêtues V4 : <strong>391,4 km</strong> (38,6 %)</li><li>Voies périurbaines V5 : <strong>178,2 km</strong> (17,6 %)</li></ul><p><strong>18,7 %</strong> — Taux de revêtement bitumineux/bétonné &nbsp;|&nbsp; <strong>10 arrondissements</strong> couverts par la cartographie</p>","content_en":"<ul><li>Primary roads V1: <strong>84.7 km</strong> (8.3%)</li><li>Secondary roads V2: <strong>141.2 km</strong> (13.9%)</li><li>Tertiary roads V3: <strong>219.8 km</strong> (21.7%)</li><li>Unpaved tracks V4: <strong>391.4 km</strong> (38.6%)</li><li>Peri-urban roads V5: <strong>178.2 km</strong> (17.6%)</li></ul><p><strong>18.7%</strong> bituminous/concrete pavement rate | <strong>10 districts</strong> covered</p>","content_ar":"<ul><li>طرق أولية V1: <strong>84.7 كم</strong> (8.3%)</li><li>طرق ثانوية V2: <strong>141.2 كم</strong> (13.9%)</li><li>طرق ثالثية V3: <strong>219.8 كم</strong> (21.7%)</li><li>مسارات غير معبدة V4: <strong>391.4 كم</strong> (38.6%)</li><li>طرق ضواحي V5: <strong>178.2 كم</strong> (17.6%)</li></ul>"},
    {"order":14,"slug":"etat-reseau-arrondissement","title_fr":"5.2 État du réseau par arrondissement","title_en":"5.2 Network Condition by District","title_ar":"5.2 حالة الشبكة حسب المقاطعة","content_fr":"<p>Le PCI moyen global de <strong>46,0</strong> classe l'ensemble du réseau dans la catégorie « Médiocre », seuil critique indiquant la nécessité d'interventions de réhabilitation majeure. Les arrondissements périphériques (7ème, 4ème, 8ème) présentent les scores les plus faibles, reflétant l'absence historique d'investissements.</p><p><strong>📊 Situation critique :</strong> Plus de 63 % du réseau routier présente un état médiocre à très mauvais (PCI &lt; 50). Le réseau se situe en-dessous du seuil critique de rentabilité de l'entretien préventif.</p>","content_en":"<p>The overall average PCI of <strong>46.0</strong> classifies the entire network in the 'Poor' category. Peripheral districts (7th, 4th, 8th) show the lowest scores.</p><p><strong>📊 Critical situation:</strong> More than 63% of the road network is in poor to very poor condition (PCI &lt; 50).</p>","content_ar":"<p>متوسط PCI الإجمالي البالغ <strong>46.0</strong> يصنف الشبكة في فئة 'سيئة'. المقاطعات الطرفية (7، 4، 8) تظهر أدنى الدرجات.</p><p><strong>📊 وضع حرج:</strong> أكثر من 63% من شبكة الطرق في حالة سيئة (PCI &lt; 50).</p>"},
    {"order":15,"slug":"analyse-spatiale","title_fr":"5.3 Analyse spatiale et zones critiques","title_en":"5.3 Spatial Analysis and Critical Zones","title_ar":"5.3 التحليل المكاني والمناطق الحرجة","content_fr":"<p>L'analyse par kernel density estimation (KDE) révèle trois clusters spatiaux :</p><ul><li><strong>Frange nord-est</strong> : 7ème arrondissement, inondations récurrentes et trafic de transit international</li><li><strong>Extensions sud-ouest</strong> : 4ème et 8ème arrondissements, urbanisation informelle sans infrastructure</li><li><strong>Marchés centraux</strong> : 1er et 3ème arrondissements, surcharge de trafic permanente</li></ul><p>L'indice de Moran global (I = 0,68 ; p &lt; 0,001) confirme une auto-corrélation spatiale positive significative.</p>","content_en":"<p>KDE analysis reveals three spatial clusters:</p><ul><li><strong>Northeast fringe:</strong> 7th district, recurrent flooding and international transit traffic</li><li><strong>Southwest extensions:</strong> 4th and 8th districts, informal urbanization without infrastructure</li><li><strong>Central markets:</strong> 1st and 3rd districts, permanent traffic overload</li></ul><p>Global Moran's index (I = 0.68; p &lt; 0.001) confirms significant positive spatial autocorrelation.</p>","content_ar":"<p>يكشف تحليل KDE عن ثلاث مجموعات مكانية: الحافة الشمالية الشرقية (مقاطعة 7)، امتدادات الجنوب الغربي (مقاطعتا 4 و 8)، والأسواق المركزية (مقاطعتا 1 و 3).</p>"},
    {"order":16,"slug":"performance-ia","title_fr":"5.4 Performance du modèle IA","title_en":"5.4 AI Model Performance","title_ar":"5.4 أداء نموذج الذكاء الاصطناعي","content_fr":"<p><strong>127 400</strong> images drone traitées automatiquement | <strong>342 800</strong> dégradations géoréférencées détectées</p><p>Répartition par type de dégradation : faïençage <strong>41,2 %</strong>, nids-de-poule <strong>28,7 %</strong>, fissures longitudinales <strong>19,4 %</strong>, orniérage <strong>10,7 %</strong>. Accord de <strong>87,3 %</strong> entre le diagnostic automatisé et l'évaluation visuelle expert.</p>","content_en":"<p><strong>127,400</strong> drone images processed automatically | <strong>342,800</strong> georeferenced damages detected</p><p>Damage distribution: cracking <strong>41.2%</strong>, potholes <strong>28.7%</strong>, longitudinal cracks <strong>19.4%</strong>, rutting <strong>10.7%</strong>. <strong>87.3%</strong> agreement between automated and expert evaluation.</p>","content_ar":"<p><strong>127,400</strong> صورة جوية معالجة تلقائياً | <strong>342,800</strong> أضرار جغرافية مرجعية مكتشفة</p><p>التوزيع: التشقق 41.2%، الحفر 28.7%، الشقوق الطولية 19.4%، الأخاديد 10.7%.</p>"},
    {"order":17,"slug":"discussion","title_fr":"6. Discussion","title_en":"6. Discussion","title_ar":"6. المناقشة","content_fr":"<p>Les résultats de cette étude démontrent la faisabilité d'une approche géomatique intégrée pour l'évaluation des infrastructures routières en contexte africain à ressources limitées.</p>","content_en":"<p>The results demonstrate the feasibility of an integrated geomatic approach for road infrastructure evaluation in resource-limited African context.</p>","content_ar":"<p>تُظهر النتائج جدوى نهج جيوماتيكي متكامل لتقييم البنية التحتية للطرق في السياق الأفريقي.</p>"},
    {"order":18,"slug":"implications-politique","title_fr":"6.1 Implications pour la politique urbaine","title_en":"6.1 Implications for Urban Policy","title_ar":"6.1 الآثار على السياسة الحضرية","content_fr":"<p>Sur la base des coûts unitaires de réhabilitation en vigueur en Afrique centrale, une estimation préliminaire situe les besoins d'investissement entre <strong>280 et 420 milliards de FCFA</strong> sur 10 ans. Cette estimation constitue une base de plaidoyer structurée pour la mobilisation de financements concessionnels auprès de la Banque mondiale, de la BAD et de l'Union européenne.</p>","content_en":"<p>Based on rehabilitation unit costs in Central Africa, investment needs are estimated between <strong>280 and 420 billion FCFA</strong> over 10 years. This constitutes a structured advocacy base for mobilizing financing from the World Bank, AfDB and EU.</p>","content_ar":"<p>تقدير أولي يضع احتياجات الاستثمار بين <strong>280 و 420 مليار فرنك أفريقي</strong> على مدى 10 سنوات.</p>"},
    {"order":19,"slug":"reproductibilite","title_fr":"6.2 Reproductibilité","title_en":"6.2 Reproducibility","title_ar":"6.2 القابلية للتكرار","content_fr":"<p>La méthodologie est conçue pour être reproductible dans d'autres villes tchadiennes (Moundou, Sarh, Abéché) et dans des contextes urbains comparables en Afrique centrale et de l'Ouest. La documentation complète sera mise à disposition en open source sur GitHub.</p>","content_en":"<p>The methodology is designed to be reproducible in other Chadian cities (Moundou, Sarh, Abéché) and comparable urban contexts in Central and West Africa. Complete documentation will be open source on GitHub.</p>","content_ar":"<p>تم تصميم المنهجية لتكون قابلة للتكرار في مدن تشادية أخرى (مندو، ساره، أبشي). ستتوفر الوثائق كمصدر مفتوح على GitHub.</p>"},
    {"order":20,"slug":"conclusion","title_fr":"7. Conclusion et Recommandations","title_en":"7. Conclusion and Recommendations","title_ar":"7. الخاتمة والتوصيات","content_fr":"<p>Cette étude constitue la <strong>première évaluation cartographique exhaustive et quantitative</strong> des infrastructures routières de N'Djamena. Elle démontre la faisabilité d'une approche géomatique intégrée pour produire, à coût maîtrisé, une information géospatiale fiable en contexte à ressources limitées.</p>","content_en":"<p>This study constitutes the <strong>first exhaustive and quantitative cartographic evaluation</strong> of N'Djamena's road infrastructure. It demonstrates the feasibility of an integrated geomatic approach to produce reliable geospatial information at controlled cost.</p>","content_ar":"<p>تشكل هذه الدراسة <strong>أول تقييم خرائطي شامل وكمي</strong> للبنية التحتية للطرق في انجمينا.</p>"},
    {"order":21,"slug":"recommandations-strategiques","title_fr":"7.1 Recommandations stratégiques","title_en":"7.1 Strategic Recommendations","title_ar":"7.1 التوصيات الاستراتيجية","content_fr":"<ul><li>Institutionnaliser la gestion des actifs routiers : créer une unité dédiée au sein de la Mairie, dotée des outils SIG développés</li><li>Prioriser les réhabilitations sur critères multicritères : PCI, IRI, trafic journalier moyen et accessibilité aux services</li><li>Intégrer le drainage dans toute intervention : aucune réhabilitation sans système d'évacuation des eaux pluviales</li><li>Réguler le trafic de poids lourds : postes de contrôle de charge à l'essieu aux entrées de ville</li><li>Actualiser régulièrement la base de données : campagnes d'évaluation bisannuelles</li><li>Mobiliser des financements internationaux via les résultats de cette étude comme document de base</li></ul>","content_en":"<ul><li>Institutionalize road asset management: create a dedicated GIS unit within City Hall</li><li>Prioritize rehabilitations on multi-criteria: PCI, IRI, daily traffic and service accessibility</li><li>Integrate drainage in all interventions: no rehabilitation without stormwater system</li><li>Regulate heavy truck traffic: axle load control posts at city entrances</li><li>Regularly update the database: biannual evaluation campaigns</li><li>Mobilize international financing using this study as base document</li></ul>","content_ar":"<ul><li>إضفاء الطابع المؤسسي على إدارة أصول الطرق</li><li>إعطاء الأولوية لإعادة التأهيل على معايير متعددة</li><li>دمج الصرف في جميع التدخلات</li><li>تنظيم حركة الشاحنات الثقيلة</li><li>تحديث قاعدة البيانات بانتظام</li><li>تعبئة التمويل الدولي</li></ul>"},
]

REFERENCES = [
    "ASTM International. (2020). ASTM D6433-20: Standard Practice for Roads and Parking Lots Pavement Condition Index Surveys.",
    "Banque mondiale. (2023). Chad Infrastructure Assessment Report. Washington D.C.",
    "Fan, R. et al. (2022). Pothole detection based on disparity transformation and road surface modeling. IEEE Transactions on Image Processing, 29, 897–908.",
    "Maeda, H. et al. (2018). Road damage detection and classification using deep neural networks. Computer-Aided Civil and Infrastructure Engineering, 33(12), 1127–1141.",
    "Mahamat, A. (2018). Mobilité urbaine et transport à N'Djamena. Revue Tchadienne de Sciences Sociales, 4(2), 12–29.",
    "Mohan, A. et al. (2021). Crack detection using image processing: A critical review. Alexandria Engineering Journal, 57(2), 787–798.",
    "Papagiannakis, A.T. & Masad, E.A. (2008). Pavement Design and Materials. Hoboken, NJ: John Wiley & Sons.",
    "PDNA. (2020). Post-Disaster Needs Assessment Rapport Inondations Tchad 2020. N'Djamena.",
    "Sayers, M.W. et al. (1986). Guidelines for Conducting and Calibrating Road Roughness Measurements. World Bank Technical Paper No. 46.",
    "Shahin, M.Y. & Kohn, S.D. (1979). Pavement Maintenance Management for Roads and Parking Lots. US Army Engineer Waterways Experiment Station.",
    "Ultralytics. (2023). YOLOv8: A New Era of Object Detection. https://github.com/ultralytics/ultralytics",
    "Yohannes, T. & Soromessa, T. (2019). Assessment of road conditions using GIS in Addis Ababa. Ethiopian Journal of Environmental Studies, 12(2), 143–157.",
    "Bambé H.P. (2026). Évaluation et Cartographie des Infrastructures Routières de N'Djamena. Revue de Géomatique & d'Ingénierie Urbaine, vol.1.",
]

KEY_METRICS = [
    {"label": "Réseau cartographié", "value": "1 015", "unit": "km",  "icon": "🛣️"},
    {"label": "PCI moyen global",    "value": "46,0",   "unit": "",    "icon": "📊"},
    {"label": "Précision modèle IA", "value": "91,3",  "unit": "%",   "icon": "🤖"},
    {"label": "Réseau en état critique", "value": "63", "unit": "%",  "icon": "⚠️"},
]

# ══════════════════════════════════════════════════════════════
#  IMPORT
# ══════════════════════════════════════════════════════════════

print("=" * 60)
print("IMPORT ARTICLE — Portfolio HPB")
print("=" * 60)

# ── Trouver l'article existant ────────────────────────────────
articles = Article.objects.all()
print(f"Articles en base : {articles.count()}")
for a in articles:
    print(f"  → {a.id} | statut={a.status} | titre={a.title_fr[:50] if a.title_fr else '(vide)'}")

if articles.count() == 0:
    print("\n❌ Aucun article en base. Créez d'abord un article dans l'admin.")
    sys.exit(1)

# Prendre le premier article (ou ajuster selon l'ID souhaité)
art = articles.first()
print(f"\n📝 Mise à jour de l'article : {art.id}")

# ── Mise à jour des champs ────────────────────────────────────
art.title_fr    = "Évaluation et Cartographie des Infrastructures Routières Urbaines de N'Djamena"
art.title_en    = "Evaluation and Mapping of Urban Road Infrastructure in N'Djamena"
art.title_ar    = "تقييم ورسم خرائط البنية التحتية للطرق الحضرية في انجمينا"
art.subtitle_fr = "Approche Multi-Source par SIG, Télédétection et Intelligence Artificielle Appliquée à la Ville de N'Djamena, Tchad"
art.subtitle_en = "Multi-Source Approach using GIS, Remote Sensing and Artificial Intelligence Applied to N'Djamena, Chad"
art.subtitle_ar = "نهج متعدد المصادر باستخدام نظم المعلومات الجغرافية والاستشعار عن بعد والذكاء الاصطناعي"
art.abstract_fr = "L'état des infrastructures routières constitue un indicateur clé du développement urbain et de la qualité de vie des populations. N'Djamena, capitale du Tchad, illustre cette problématique avec un réseau routier de plus de 1 000 km dont la majorité est en état médiocre à critique. Cette étude propose une approche méthodologique intégrée combinant SIG, photogrammétrie drone GNSS RTK et deep learning (YOLOv8) pour cartographier, évaluer et analyser l'ensemble du réseau routier. Les résultats révèlent que 63 % du réseau présente un PCI inférieur à 50 (médiocre à très mauvais), avec une concentration spatiale dans les arrondissements périphériques. Le modèle IA atteint une précision mAP@0.5 de 91,3 %. Cette étude constitue la première évaluation cartographique exhaustive des infrastructures routières de N'Djamena."
art.abstract_en = "The condition of road infrastructure is a key indicator of urban development and quality of life. N'Djamena illustrates this issue with a road network of over 1,000 km, mostly in poor to critical condition. This study proposes an integrated methodological approach combining GIS, drone GNSS RTK photogrammetry and deep learning (YOLOv8) to map, assess and analyze the entire road network. Results reveal 63% of the network has PCI below 50, with spatial concentration in peripheral districts. The AI model achieves 91.3% mAP@0.5 accuracy."
art.abstract_ar = "يُعد حالة البنية التحتية للطرق مؤشراً رئيسياً للتنمية الحضرية ونوعية حياة السكان. تجسد نجامينا، عاصمة تشاد، هذه المشكلة بشبكة طرق تزيد مسافتها عن 1000 كيلومتر، معظمها في حالة متوسطة إلى سيئة. تقترح هذه الدراسة نهجًا منهجيًا متكاملًا يجمع بين GIS والتصوير المساحي بالطائرات بدون طيار والتعلم العميق (YOLOv8). النتائج: 63% من الشبكة بمؤشر PCI أقل من 50، ودقة نموذج الذكاء الاصطناعي 91.3%."
art.keywords_fr = "GIS, PCI, IRI, Télédétection, Intelligence Artificielle, N'Djamena, Géomatique urbaine"
art.keywords_en = "GIS, PCI, IRI, Remote Sensing, Artificial Intelligence, N'Djamena, Urban Geomatics"
art.keywords_ar = "GIS, PCI, IRI, استشعار عن بعد, ذكاء اصطناعي, انجمينا, جيوماتيكا حضرية"
art.journal_name= "Revue de Géomatique & d'Ingénierie Urbaine"
art.volume      = "Vol. 1"
art.year        = 2026
art.doi         = "10.kiceko/hpb.2026.routier-ndjamena"
art.status      = "published"
art.meta_description_fr = "L'état des infrastructures routières constitue un indicateur clé du développement urbain. N'Djamena illustre cette problématique avec un réseau routier de plus de 1 000 km en état critique."
art.meta_description_en = "Road infrastructure condition is a key indicator of urban development. N'Djamena illustrates this with a 1,000+ km road network mostly in poor condition."

art.content_sections = CONTENT_SECTIONS
art.references       = REFERENCES
art.key_metrics      = KEY_METRICS

# Dates
if not art.published_at:
    art.published_at = timezone.now()

art.save()
print("✅ Article mis à jour avec succès !")
print(f"   - {len(CONTENT_SECTIONS)} sections de contenu")
print(f"   - {len(REFERENCES)} références bibliographiques")
print(f"   - {len(KEY_METRICS)} statistiques clés")

# ── Auteur ────────────────────────────────────────────────────
print("\n📌 Vérification de l'auteur...")
author, created = Author.objects.get_or_create(
    first_name="Hilla Prince",
    last_name="Bambé",
    defaults={
        "title": "M.",
        "affiliation": "KICEKO CONSULTANT · N'Djamena, Tchad",
        "country": "Tchad",
        "is_corresponding": True,
    }
)
if created:
    print("✅ Auteur créé : M. Hilla Prince Bambé")
else:
    print("ℹ️  Auteur existant : M. Hilla Prince Bambé")

# Lier l'auteur à l'article si pas déjà fait
aa, created = ArticleAuthor.objects.get_or_create(
    article=art, author=author,
    defaults={"order": 1}
)
if created:
    print("✅ Auteur lié à l'article")
else:
    print("ℹ️  Lien auteur-article déjà existant")

# ── Résumé final ──────────────────────────────────────────────
print("\n" + "=" * 60)
print("IMPORT TERMINÉ ✅")
print("=" * 60)
print(f"URL article : http://localhost:5173/articles/{art.id}")
print(f"Admin       : http://localhost:8000/admin/api/article/{art.id}/change/")
print("=" * 60)
